# Autograd: automatic differentiation

The ``autograd`` package provides automatic differentiation for all operations
on Tensors. It is a define-by-run framework, which means that your backprop is
defined by how your code is run, and that every single iteration can be
different.

In [1]:
import torch

Create a tensor:

In [2]:
x = torch.tensor([[1, 2], [3, 4]], requires_grad=True, dtype=torch.float32)
print(x)

tensor([[ 1.,  2.],
        [ 3.,  4.]])


Do an operation on the tensor:

In [3]:
y = x - 2
print(y)

tensor([[-1.,  0.],
        [ 1.,  2.]])


``y`` was created as a result of an operation, so it has a ``grad_fn``.



In [4]:
print(y.grad_fn)

In [5]:
print(x.grad_fn)

None


In [6]:
y.grad_fn

In [7]:
y.grad_fn.next_functions[0][0]

In [8]:
y.grad_fn.next_functions[0][0].variable

tensor([[ 1.,  2.],
        [ 3.,  4.]])

Do more operations on `y`

In [9]:
z = y * y * 3
out = z.mean()

print(z, out)

(tensor([[  3.,   0.],
        [  3.,  12.]]), tensor(4.5000))


## Gradients

Let's backprop now `out.backward()` is equivalent to doing `out.backward(torch.tensor([1.0]))`

In [10]:
out.backward()

print gradients d(out)/dx




In [11]:
print(x.grad)

tensor([[-1.5000,  0.0000],
        [ 1.5000,  3.0000]])


You can do many crazy things with autograd!
> With Great *Flexibility* Comes Great Responsibility

In [12]:
# Dynamic graphs!
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([ -941.4715,  -144.5049,  1462.4211])


In [13]:
gradients = torch.FloatTensor([0.1, 1.0, 0.0001])
y.backward(gradients)

print(x.grad)

tensor([  102.4000,  1024.0000,     0.1024])


## Inference

In [ ]:
n = 3

In [ ]:
x = torch.arange(1, n + 1, requires_grad=True)
w = torch.ones(n, requires_grad=True)
z = w @ x
z.backward()
print(x.grad, w.grad, sep='\n')

In [ ]:
x = torch.arange(1, n + 1)
w = torch.ones(n, requires_grad=True)
z = w @ x
z.backward()
print(x.grad, w.grad, sep='\n')

In [ ]:
with torch.no_grad():
    x = torch.arange(1, n + 1)
    w = torch.ones(n, requires_grad=True)
    z = w @ x
    z.backward()
    print(x.grad, w.grad, sep='\n')

## More stuff

Documentation of the automatic differentiation package is at
http://pytorch.org/docs/autograd

