
# What is PyTorch?

It’s a Python based scientific computing package targeted at two sets of audiences:

-  Tensorial library that uses the power of GPUs
-  A deep learning research platform that provides maximum flexibility and speed

## Import the library

In [1]:
import torch  # <Ctrl> / <Shift> + <Return>

## Getting help in Jupyter

In [ ]:
torch.sq  # <Tab>

In [2]:
# What about all `*Tensor`s?
torch.*Tensor?

torch.ByteTensor
torch.CharTensor
torch.DoubleTensor
torch.FloatTensor
torch.HalfTensor
torch.IntTensor
torch.LongTensor
torch.ShortTensor
torch.Tensor

In [ ]:
torch.nn.Module()  # <Shift>+<Tab>

In [ ]:
# Annotate your functions / classes!
torch.nn.Module?

In [ ]:
torch.nn.Module??

## Dropping to Bash: magic!

In [ ]:
! ls -lh

In [ ]:
%%bash
for f in $(ls *.*); do
    echo $(wc -l $f)
done

In [ ]:
# Help?
%%bash?

In [ ]:
# Getting some general help
%magic

## Python native data types

Python has many native datatypes. Here are the important ones:

 - **Booleans** are either `True` or `False`.
 - **Numbers** can be integers (1 and 2), floats (1.1 and 1.2), fractions (1/2 and 2/3), or even complex numbers.
 - **Strings** are sequences of Unicode characters, e.g. an html document.
 - **Lists** are ordered sequences of values.
 - **Tuples** are ordered, immutable sequences of values.
 - **Sets** are unordered bags of values.
 - **Dictionaries** are unordered bags of key-value pairs.
 
See [here](http://www.diveintopython3.net/native-datatypes.html) for a complete overview.

### More resources

 1. Brief Python introduction [here](https://learnxinyminutes.com/docs/python3/).
 2. Full Python tutorial [here](https://docs.python.org/3/tutorial/).
 3. A Whirlwind Tour of Python [here](https://github.com/jakevdp/WhirlwindTourOfPython).
 4. Python Data Science Handbook [here](https://github.com/jakevdp/PythonDataScienceHandbook).

## Torch!

In [3]:
t = torch.Tensor(2, 3, 4)
type(t)

torch.Tensor

In [4]:
t.size()

torch.Size([2, 3, 4])

In [ ]:
# t.size() is a classic tuple =>
print('t size:', ' \u00D7 '.join(map(str, t.size())))

In [ ]:
print(f'point in a {t.numel()} dimensional space')
print(f'organised in {t.dim()} sub-dimensions')

In [5]:
t

tensor([[[ 0.4533,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000]],

        [[ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000]]])

In [6]:
# Mind the underscore!
t.random_(10)

tensor([[[ 1.,  5.,  1.,  0.],
         [ 3.,  9.,  4.,  2.],
         [ 8.,  3.,  5.,  3.]],

        [[ 4.,  6.,  0.,  1.],
         [ 0.,  1.,  1.,  4.],
         [ 9.,  4.,  8.,  4.]]])

In [7]:
t

tensor([[[ 1.,  5.,  1.,  0.],
         [ 3.,  9.,  4.,  2.],
         [ 8.,  3.,  5.,  3.]],

        [[ 4.,  6.,  0.,  1.],
         [ 0.,  1.,  1.,  4.],
         [ 9.,  4.,  8.,  4.]]])

In [8]:
r = torch.Tensor(t)
r.resize_(3, 8)
r

tensor([[ 1.,  5.,  1.,  0.,  3.,  9.,  4.,  2.],
        [ 8.,  3.,  5.,  3.,  4.,  6.,  0.,  1.],
        [ 0.,  1.,  1.,  4.,  9.,  4.,  8.,  4.]])

In [9]:
r.zero_()

tensor([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [10]:
t

tensor([[[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]]])

In [11]:
# This *is* important, sigh...
s = r.clone()

In [12]:
s.fill_(1)
s

tensor([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [13]:
r

tensor([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

## Vectors (1D Tensors)

In [14]:
v = torch.Tensor([1, 2, 3, 4]); v

tensor([ 1.,  2.,  3.,  4.])

In [ ]:
print(f'dim: {v.dim()}, size: {v.size()[0]}')

In [15]:
w = torch.Tensor([1, 0, 2, 0]); w

tensor([ 1.,  0.,  2.,  0.])

In [16]:
# Element-wise multiplication
v * w

tensor([ 1.,  0.,  6.,  0.])

In [18]:
# Scalar product: 1*1 + 2*0 + 3*2 + 4*0
torch.dot(v, w)

tensor(7.)

In [19]:
x = torch.Tensor(5).random_(10); x

tensor([ 1.,  4.,  2.,  5.,  7.])

In [ ]:
print(f'first: {x[0]}, last: {x[-1]}')

In [ ]:
# Extract sub-Tensor [from:to)
x[1:2 + 1]

In [20]:
v

tensor([ 1.,  2.,  3.,  4.])

In [21]:
v = torch.arange(1, 4 + 1); v

tensor([ 1.,  2.,  3.,  4.])

In [22]:
print(v.pow(2), v)

(tensor([  1.,   4.,   9.,  16.]), tensor([ 1.,  2.,  3.,  4.]))


In [23]:
print(v.pow_(2), v)

(tensor([  1.,   4.,   9.,  16.]), tensor([  1.,   4.,   9.,  16.]))


## Matrices (2D Tensors)

In [24]:
m = torch.Tensor([[2, 5, 3, 7],
                  [4, 2, 1, 9]]); m

tensor([[ 2.,  5.,  3.,  7.],
        [ 4.,  2.,  1.,  9.]])

In [25]:
m.dim()

2

In [26]:
print(m.size(0), m.size(1), m.size(), sep=' -- ')

SyntaxError: invalid syntax (<ipython-input-26-349170eb1a98>, line 1)

In [27]:
m.numel()

8

In [28]:
m[0][2]

tensor(3.)

In [29]:
m[0, 2]

tensor(3.)

In [30]:
m[:, 1]

tensor([ 5.,  2.])

In [50]:
m[:, [1]]

tensor([[ 5.],
        [ 2.]])

In [51]:
m[[0], :]

tensor([[ 2.,  5.,  3.,  7.]])

In [52]:
m[0, :]

tensor([ 2.,  5.,  3.,  7.])

In [53]:
v = torch.arange(1, 4 + 1); v

tensor([ 1.,  2.,  3.,  4.])

In [55]:
m @ v

RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)

In [49]:
m[[0], :] @ v

RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)

In [40]:
m[[1], :] @ v

SyntaxError: invalid syntax (<ipython-input-40-1781f5ff2ad4>, line 1)

In [41]:
m + torch.rand(2, 4)

tensor([[ 2.1477,  5.3276,  3.2858,  7.3374],
        [ 4.3630,  2.4544,  1.9862,  9.3208]])

In [42]:
m - torch.rand(2, 4)

tensor([[ 1.2144,  4.0708,  2.9537,  6.0135],
        [ 3.7324,  1.8705,  0.0181,  8.7393]])

In [43]:
m * torch.rand(2, 4)

tensor([[ 1.1302,  3.2455,  0.2096,  2.3525],
        [ 2.0550,  1.9819,  0.5785,  7.8024]])

In [44]:
m / torch.rand(2, 4)

tensor([[  4.8112,   6.9930,  17.9380,   8.7894],
        [  5.1256,   2.4675,   1.5231,  26.7904]])

In [56]:
m.t()

tensor([[ 2.,  4.],
        [ 5.,  2.],
        [ 3.,  1.],
        [ 7.,  9.]])

In [57]:
# Same as
m.transpose(0, 1)

tensor([[ 2.,  4.],
        [ 5.,  2.],
        [ 3.,  1.],
        [ 7.,  9.]])

## Constructors

In [58]:
torch.arange(3, 8 + 1)

tensor([ 3.,  4.,  5.,  6.,  7.,  8.])

In [59]:
torch.arange(5.7, -3, -2.1)

tensor([ 5.7000,  3.6000,  1.5000, -0.6000, -2.7000])

In [60]:
torch.linspace(3, 8, 20).view(1, -1)

tensor([[ 3.0000,  3.2632,  3.5263,  3.7895,  4.0526,  4.3158,  4.5789,
          4.8421,  5.1053,  5.3684,  5.6316,  5.8947,  6.1579,  6.4211,
          6.6842,  6.9474,  7.2105,  7.4737,  7.7368,  8.0000]])

In [61]:
torch.zeros(3, 5)

tensor([[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]])

In [62]:
torch.ones(3, 2, 5)

tensor([[[ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.]],

        [[ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.]],

        [[ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.]]])

In [63]:
torch.eye(3)

tensor([[ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  0.,  1.]])

In [64]:
# Pretty plotting config
%run plot_conf.py

ERROR:root:File `u'plot_conf.py'` not found.


In [65]:
plt_style()

NameError: name 'plt_style' is not defined

In [ ]:
# Numpy bridge!
plt.hist(torch.randn(1000).numpy(), 100);

In [ ]:
plt.hist(torch.randn(10**6).numpy(), 100);  # how much does this chart weight?
# use rasterized=True for SVG/EPS/PDF!

In [ ]:
plt.hist(torch.rand(10**6).numpy(), 100);

## Casting

In [66]:
torch.*Tensor?

torch.ByteTensor
torch.CharTensor
torch.DoubleTensor
torch.FloatTensor
torch.HalfTensor
torch.IntTensor
torch.LongTensor
torch.ShortTensor
torch.Tensor

In [67]:
m

tensor([[ 2.,  5.,  3.,  7.],
        [ 4.,  2.,  1.,  9.]])

In [68]:
m.double()

tensor([[ 2.,  5.,  3.,  7.],
        [ 4.,  2.,  1.,  9.]], dtype=torch.float64)

In [69]:
m.byte()

tensor([[ 2,  5,  3,  7],
        [ 4,  2,  1,  9]], dtype=torch.uint8)

In [70]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
m.to(device)

tensor([[ 2.,  5.,  3.,  7.],
        [ 4.,  2.,  1.,  9.]])

In [71]:
m_np = m.numpy(); m_np

array([[2., 5., 3., 7.],
       [4., 2., 1., 9.]], dtype=float32)

In [72]:
m_np[0, 0] = -1; m_np

array([[-1.,  5.,  3.,  7.],
       [ 4.,  2.,  1.,  9.]], dtype=float32)

In [73]:
m

tensor([[-1.,  5.,  3.,  7.],
        [ 4.,  2.,  1.,  9.]])

In [75]:
import numpy as np
n_np = np.arange(5)
n = torch.from_numpy(n_np)
print(n_np, n)

(array([0, 1, 2, 3, 4]), tensor([ 0,  1,  2,  3,  4]))


In [76]:
n.mul_(2)
n_np

array([0, 2, 4, 6, 8])

## More fun

In [77]:
a = torch.Tensor([[1, 2, 3, 4]])
b = torch.Tensor([[5, 6, 7, 8]])
print(a, b)

(tensor([[ 1.,  2.,  3.,  4.]]), tensor([[ 5.,  6.,  7.,  8.]]))


In [78]:
torch.cat((a, b), 0)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]])

In [79]:
torch.cat((a, b), 1)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.]])

## Much more

There's definitely much more, but this was the basics about `Tensor`s fun.

*Torch* full API should be read at least once.
Hence, go [here](http://pytorch.org/docs/0.3.0/torch.html).
You'll find 100+ `Tensor` operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described.